### ISSUE TITLE
There is no libtimsdata.so file

### ISSUE THREAD

**Issue by QingzuHe** [Roestlab/dia-pasef#25]
Hello,
I am a postgraduate student. Recently, I want to use diapysef to convert tdf file. However, Bruker sdk is not found. The libtimsdata.so is just a link file in diapysef. Which URL do I need to download? Can you tell me? 
Thank you very much!!

**Comment by klannieha** [comment]
The sdk file is specifically vendor distributed and has not been publicly freely accessible yet, it might be best contacting Bruker for the file.

**Comment by cbielow** [comment]
there is another package (`timsdata`), which seems to contain the file.
Just download https://github.com/MatteoLacki/timsdata/blob/master/timsdata/cpp/libtimsdata.so
and put in your working directory (other places might be fine as well).

**Comment by QingzuHe** [comment]
已收到，谢谢！
