### ISSUE TITLE
DEFINE src

### ISSUE THREAD

**Issue by BJWiley233** [Roestlab/dia-pasef#38]
This is not the best message to display.  "src" could literally mean `src` folder for diapasef, or it could metaphorically mean a source folder of a project.  Define `src` please for those who many not be Native English speaking people.

```
To activate that functionality place libtimsdata.so (Linux) or timsdata.dll in the src folder. 
```

Also maybe if possible indicate where to place if installing from pip...
```
$ ls /usr/local/lib/python3.7/site-packages/diapysef*                      
/usr/local/lib/python3.7/site-packages/diapysef:
__init__.py             data               plotting.py                                          two_dimension_gradient_ascent_peak_finder.py
__pycache__             diapysef.py        proto_two_dimension_gradient_ascent_peak_finding.py  two_dimension_gradient_ascent_peak_finding.py
conversions.py          main.py            splitting_consumer.py                                two_dimension_quantification.py
convert_tdf_to_mzml.py  merge_consumer.py  targeted_data_extraction.py                          util.py
coverage.py             pasefdata.py       timsdata.py

/usr/local/lib/python3.7/site-packages/diapysef-1.0.1.dist-info:
INSTALLER  METADATA  RECORD  REQUESTED  WHEEL  entry_points.txt  top_level.txt
```

**Comment by singjc** [comment]
Hi,

Thank you for your suggestion, I agree the message is not very helpful or self explanatory. Depending on how you are using diapysef, you just need to have the bruker library be in the same working directory that you are working from.

What part of diapysef were you trying to use? The CLI (command line interface)? I recently added to the CLI to automatically download the bruker library if it is not found in the working directory the command is called from.

Hope this helps.

Best,

Justin
